### ISSUE TITLE
Inconsistent bug with Kinggrinyov's mods (Dragon Ball Characters)

### ISSUE THREAD

**Issue by 4AC11** [KingEnderBrine/-RoR2-ExtendedLoadout#10]
After doing the basics of adding each skill with a ^ to the config file, we opened our modpack and everything worked just fine, the extra skills appeared as normal, and other than the somewhat known issue of not being able to charge moves, everything works flawlessly. Then, randomly, upon opening the game one day, the skills vanished from the Loadout page.... But not from the skills page. My friend, who already had extra skills selected, was still able to use them, they just were missing from his HUD and the loadout page. However, I didn't select any skills before this bug occurred, and so I can't make any use of any of them. 

Example of my current problem:
![image](https://github.com/KingEnderBrine/-RoR2-ExtendedLoadout/assets/97819008/0c2a6f6d-5cee-4468-a080-4a2b3646584f)
No skills appear in the Loadout page at all.
![image](https://github.com/KingEnderBrine/-RoR2-ExtendedLoadout/assets/97819008/091fe3a3-483d-4def-a97c-4332ab24dee5)
However, they are visible in the Skills page. Since they are disabled by default, and I can't interact with them on the Loadout page, the skills are inaccessible to me. This is the case for all three DB characters.

I have no idea why this is happening of whether its something that can be fixed on this mod's end, but even just knowing why it randomly flips between visible and invisible on the loadout page would be helpful.

**Comment by KingEnderBrine** [comment]
That's a known thing, it was always like that and that's an issue on their side, nothing I can do about it. It's not visible on loadout page because of a hacky way in which skin buttons are shown fot these characters.
