### ISSUE TITLE
UI bug when selecting skills

### ISSUE THREAD

**Issue by benjdidj** [KingEnderBrine/-RoR2-ExtendedLoadout#4]
When clicking a new skill the square outline does not follow so the skill doesnt seem selected... but it is. not that big of a deal. i've seen some older survivor mods do that.

**Comment by KingEnderBrine** [comment]
It works perfectly fine when only this mod installed. Probably something else breaks it. I can't help without a log.

**Comment by benjdidj** [comment]
ok ill try to see whats up.

**Comment by benjdidj** [comment]
You are right, it is because of a survivor with bugged UI, probably megaman. that has no additional skin. other survivor had this problembefore because of the no skin bug. Sorry for the inconvenience .
