### ISSUE TITLE
Unsupported character mod

### ISSUE THREAD

**Issue by freedom-cry** [KingEnderBrine/-RoR2-ExtendedLoadout#7]
This mod doesn't work with mod SniperClassic by EnforcerGang.I can't see Sniper in the config files.

**Comment by KingEnderBrine** [comment]
Published an update, but I should warn you that some skills on modded characters might still not work, or work not like you would expect them and there's nothing I can do about that. For example Sniper's second M1 skill doesn't reload when selected as extra skill
